### ISSUE TITLE
Show Completed Events does not work in beta version

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/widget-google-calendar#83]
Completed events do not show up regardless of whether the option is checked or not.

Toggled back and forth several times (saving and publishing after each) and the results do not change.

Verified the calendar xml feed contains the completed/past events.

**Comment by donnapep** [comment]
@mfisher11 Please provide a URL to a sample Presentation. @alanclayton Can this be a standard practice to eliminate some of the back and forth?

Thx.

**Comment by mfisher11** [comment]
Calendar ID used in settings:  risevision.com_lutal6o71adatn07ob7puhl2hs@group.calendar.google.com
XML feed: https://www.google.com/calendar/feeds/risevision.com_lutal6o71adatn07ob7puhl2hs%40group.calendar.google.com/public/basic

http://preview.risevision.com/Viewer.html?type=presentation&id=3cd75386-e723-46f5-9806-0da8c880ad7c

**Comment by donnapep** [comment]
@mfisher11 Thanks, can you link the Manage Presentation link too? I like to just take my own copy of that.

**Comment by mfisher11** [comment]
http://rva.risevision.com/#PRESENTATION_MANAGE/id=3cd75386-e723-46f5-9806-0da8c880ad7c/company=e514fd51-fadd-4e19-94af-f92549772c7f

**Comment by donnapep** [comment]
@mfisher11 Can you clarfiy where the problem lies? The first event I see is for next Wednesday. I do not see any events for today.

Also, the test URL is using `https`. It should be `http`.

Thx.

**Comment by mfisher11** [comment]
I assume you're talking about the gadget URLs?
http://s3.amazonaws.com/widget-google-calendar-test/0.1.0/dist/widget.html   and
http://s3.amazonaws.com/widget-google-calendar-test/0.1.0/dist/settings.html ?

I just changed them to http and it didn't make any difference.  In the presentation's gadget config, I'm specifying the calendar ID and not a URL.  I provided the google.com link as a direct way to verify the xml that google is providing.

There is a single back-dated event titled "Past event (maybe completed?)"  that was scheduled for Jan 14) and is not showing up in production or in any combination of the settings in beta.    It's possible that the creation date is taken into consideration...

Thanks.

**Comment by donnapep** [comment]
@mfisher11 Yes, those are the URLs I mean. If you go into the HTML view of the Presentation that you provided the link for, you will see that it is still using `https` - http://www.screencast.com/t/FnXsDsRl. If the Production links are using `http`, then `http` should be used for the test version of the Widget as well. Right now when I try to preview the Presentation you've linked to, the Widget on the right doesn't even show, and that's because of the `https` issue.

Back to the issue at hand, if I take a copy of your Presentation and change `https` to `http` I see this - http://screencast.com/t/CbBdzVSWOlx. I don't see any event with a date of Jan. 14th on it. The first event I see is for Jan. 21st. So I really don't see a problem here. The Widget has never shown events in the past, even before this change. They always start at today. So if you want to test that completed events are not showing, you need to have an event for today that is early enough that it has already ended by the time you run the Presentation.

Thx.

**Comment by donnapep** [comment]
@mfisher11 I think I've figured out what you are trying to say. I believe you are expecting events on previous days to show up. That is not how this Widget works. If that were the case, it would show events back from the beginning of time and never get to today's events. So see my point above testing completed events by ensuring *today's* completed events don't show.

Thx.

**Comment by mfisher11** [comment]
I'll fix the references to https, but the odd thing was that (aside from my misunderstanding about the subject of this bug report) the beta version always displayed fine and as expected both as a preview and on my display.

Regarding the viewing of past events, you're right--I never saw that in production, either, but that's what I thought this feature was enabling...   I'll create an appropriate event and look for it.  When I inevitably get the correct results I'll update paper trail and close this out.

Sorry about the confusion.

**Comment by mfisher11** [comment]
Closing ticket due to ambiguity and misunderstandings of the feature.  A new issue tracker will be created with better details and description of an existing but different issue.
